name: Build and Push Next.js Docker Image to GHCR

on:
  push:
    branches:
      - main # 根据你的主分支设置，可能是 master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # 允许推送到 GitHub Container Registry

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/johanchow/homework-console:latest
            ghcr.io/johanchow/homework-console:${{ github.sha }}
